# # Ubuntu 14.04 Trusty support
# dist: trusty
# sudo: required

language: cpp

# Enables the caching support to speed up compilations
# cache: ccache

compiler:
    - gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libboost-all-dev libglew-dev libwxgtk3.0-dev
    - sudo apt-get install -y freeglut3-dev swig libglm-dev libcairo2-dev

install:
    - mkdir build
    - cd build
    - cmake ../
    - make common
    - make pcbnew
    - make
    - make MyTests

script:
    - ./tests/MyTests
