language: cpp

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake make libboost-all-dev libglew-dev freeglut3-dev
    - sudo apt-get install -y swig libglm-dev libcairo2-dev

install:
    - mkdir build
    - cd build
    - cmake ../
    - make MyTests

script:
    - ./tests/MyTests

compiler:
    -clang
    -gcc
