language: cpp

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake make boost glew glut swig glm cairo

install:
    - mkdir build
    - cd build
    - cmake ../
    - make MyTests

script:
    - ./tests/MyTests

compiler:
    -clang
    -gcc
